version: '3.4'
services:
  swoft:
    image: hyperf/hyperf:7.4-alpine-v3.11-swoole
    container_name: hyperf
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - TIMEZONE=Asia/Shanghai
    restart: always
    ports:
      - "9501:9501"
      - "9504:9504"
    volumes:
      - ./:/var/www/hyperf
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - mynet
networks:
  mynet:
    external: true




